spring:
  application:
    name: aggregator
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: aggregator-group
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: ru.practicum.kafka.serializer.GeneralAvroDeserializer
      properties:
        specific.avro.value.class: ru.practicum.ewm.stats.avro.UserActionAvro
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: ru.practicum.kafka.serializer.GeneralAvroSerializer

kafka:
  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.kafka: INFO