spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${COMPILATION_DB_URL:jdbc:postgresql://compilation-db:5432/compilation}
    username: ${COMPILATION_DB_USER:postgres}
    password: ${COMPILATION_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update