spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ewm_event
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  application:
    name: event-service

  # Настройки для Config Server через Eureka
  config:
    import: "optional:configserver:"  # ← убрали прямой URL
  cloud:
    config:
      discovery:
        enabled: true                 # ← включаем discovery
        service-id: config-server     # ← имя сервиса в Eureka
      fail-fast: true
      retry:
        max-attempts: 10
        max-interval: 2000
        initial-interval: 1000

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

feign:
  httpclient:
    enabled: false
  hc5:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

grpc:
  client:
    collector-service:
      address: 'discovery:///collector-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    analyzer-service:
      address: 'discovery:///analyzer-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
  server:
    port: 0

logging:
  level:
    ru.practicum: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org.springframework.web: INFO
    io.grpc: DEBUG
    net.devh.boot.grpc: DEBUG