spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: main-service-route
          uri: lb://main-service
          predicates:
            - Path=/**
        - id: stats-server-route
          uri: lb://stats-server
          predicates:
            - Path=/stat/**
          filters:
            - RewritePath=/stat/(?<remaining>.*), /${remaining}

server:
  port: 8081