management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info

spring:
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/events/**, /admin/events/**, /users/**

        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/categories/**, /admin/categories/**

        - id: compilation-service
          uri: lb://compilation-service
          predicates:
            - Path=/compilations/**, /admin/compilations/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**, /users/**

        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**, /admin/events/*/requests/**

        - id: stats-service
          uri: lb://stats-service
          predicates:
            - Path=/hit, /stats, /stat/**

        - id: discovery-server
          uri: lb://discovery-server
          predicates:
            - Path=/eureka/**

        - id: config-server
          uri: lb://config-server
          predicates:
            - Path=/config/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG