spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: stats-server-route
          uri: lb://stats-server
          predicates:
            - Path=/stat/**
          filters:
            - RewritePath=/stat/(?<remaining>.*), /${remaining}
        - id: main-service-route
          uri: lb://main-service
          predicates:
            - Path=/**
  config:
    import: "configserver:"

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/