spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6543/ewm
spring.datasource.username=ewm
spring.datasource.password=ewm
spring.jpa.hibernate.ddl-auto=create-drop

stat.client.url=http://stat-server:9090