spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://ewm-db:5432/ewm}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create-drop