spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${REQUEST_DB_URL:jdbc:postgresql://request-db:5432/request}
    username: ${REQUEST_DB_USER:postgres}
    password: ${REQUEST_DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update