services:
  discovery-server:
    build: ./infra/discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - app-network

  config-server:
    build: ./infra/config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      discovery-server:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    networks:
      - app-network

  gateway-server:
    build: ./infra/gateway-server
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    networks:
      - app-network

  # Статистика
  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6642:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d stats" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  stats-server:
    build: stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      - DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - DATASOURCE_USERNAME=stats
      - DATASOURCE_PASSWORD=stats
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka
    networks:
      - app-network

  # БД для микросервисов
  user-db:
    image: postgres:16.1
    container_name: user-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  category-db:
    image: postgres:16.1
    container_name: category-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: category
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d category" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  event-db:
    image: postgres:16.1
    container_name: event-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: event
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d event" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  request-db:
    image: postgres:16.1
    container_name: request-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: request
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d request" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  compilation-db:
    image: postgres:16.1
    container_name: compilation-db
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: compilation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d compilation" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # Микросервисы
  user-service:
    build: ./core/user-service
    container_name: user-service
    depends_on:
      user-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      - USER_DB_URL=jdbc:postgresql://user-db:5432/user
      - USER_DB_USER=postgres
      - USER_DB_PASSWORD=postgres
      - EUREKA_URL=http://discovery-server:8761/eureka/
    networks:
      - app-network

  category-service:
    build: ./core/category-service
    container_name: category-service
    depends_on:
      category-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      - CATEGORY_DB_URL=jdbc:postgresql://category-db:5432/category
      - CATEGORY_DB_USER=postgres
      - CATEGORY_DB_PASSWORD=postgres
      - EUREKA_URL=http://discovery-server:8761/eureka/
    networks:
      - app-network

  event-service:
    build: ./core/event-service
    container_name: event-service
    depends_on:
      event-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      - EVENT_DB_URL=jdbc:postgresql://event-db:5432/event
      - EVENT_DB_USER=postgres
      - EVENT_DB_PASSWORD=postgres
      - EUREKA_URL=http://discovery-server:8761/eureka/
    networks:
      - app-network

  request-service:
    build: ./core/request-service
    container_name: request-service
    depends_on:
      request-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      - REQUEST_DB_URL=jdbc:postgresql://request-db:5432/request
      - REQUEST_DB_USER=postgres
      - REQUEST_DB_PASSWORD=postgres
      - EUREKA_URL=http://discovery-server:8761/eureka/
    networks:
      - app-network

  compilation-service:
    build: ./core/compilation-service
    container_name: compilation-service
    depends_on:
      compilation-db:
        condition: service_healthy
      discovery-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      - COMPILATION_DB_URL=jdbc:postgresql://compilation-db:5432/compilation
      - COMPILATION_DB_USER=postgres
      - COMPILATION_DB_PASSWORD=postgres
      - EUREKA_URL=http://discovery-server:8761/eureka/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge