spring:
  application:
    name: gateway-server
  config:
    import: "configserver:"  # ← убрать URL
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true          # ← включить discovery
        service-id: config-server
      retry:
        useRandomPolicy: true
        max-interval: 6000

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${random.value}