spring:
  application:
    name: main-service
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: config-server
      retry:
        useRandomPolicy: true
        max-interval: 6000

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}